### ISSUE TITLE
Use_Typo_Metrics - Possible Typo re OS/2 table value

### ISSUE THREAD

**Issue by jjsomanytabs** [googlefonts/googlefonts.github.io#139]
In the Vertical metrics guide ([link](https://googlefonts.github.io/gf-guide/metrics.html#5-use_typo_metrics-must-be-enabled)), it states:

    In the OS/2 table: `<fsSelection value="00000000 10000000"/>`

However, since Use_Typo_Metrics is governed by **bit 7**, shouldn't the correct value be `"00000000 01000000"`?

**Comment by NightFurySL2001** [comment]
Bits start counting from bit 0. The documentation is correct. Ref: https://learn.microsoft.com/en-us/typography/opentype/spec/os2#fss

**Comment by vv-monsalve** [comment]
@jjsomanytabs, thanks for opening this issue. However, as @NightFurySL2001 says, it is correct.
