### ISSUE TITLE
GF Latin Kernel glyphset?

### ISSUE THREAD

**Issue by NightFurySL2001** [googlefonts/googlefonts.github.io#44]
This page describes the glyphset for Google Font submission: https://googlefonts.github.io/gf-guide/requirements.html#glyphsets . There is a new GF Latin Kernel but it points to a 404 page. (https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/latin-kernel)

This is a clone of issue at https://github.com/google/fonts/issues/4998. Please inform if I opened the issue in the wrong repo.

**Comment by NightFurySL2001** [comment]
Closed as https://github.com/googlefonts/googlefonts.github.io/commit/12c6a5a055d2361bba7bb1c917d088f5b60e1032 .

**Comment by RosaWagner** [comment]
Yes 👍 Ah you already opened there, good.
