### ISSUE TITLE
Virtual environment activation

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/googlefonts.github.io#46]
In the section in "Setting up a Working Environment" I note the command for setting up a virtual environment creates it with the name `myenv`, but the activate code activates one under `env`. 

``` 
python3 -m venv myenv

source env/bin/activate

env\Scripts\activate.bat

```

To avoid confusion, it would probably be best to make these the same so if someone unfamiliar with coding is just copy / pasting.

**Comment by aaronbell** [comment]
Looks like there's also a typo a little further down:

`It is not recommended to instal virtual environments in clouds, drives, dropbox, etc.`
Should be "install" :)

**Comment by RosaWagner** [comment]
I am seeing all these issues now. thanks Aaron for the review, tbh feel free to correct directly in a PR, it probably take the same amount of time as opening issues ;)

**Comment by vv-monsalve** [comment]
Seems already solved.
