### ISSUE TITLE
gftools packager documentation needs improvement

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/googlefonts.github.io#55]
Following the instructions here: https://googlefonts.github.io/gf-guide/making-pr.html and here: https://googlefonts.github.io/gf-guide/package.html on a Mac M1 12.5.1 I get the following error: 

```
MINI-M1 🌎 ~/Google/gf-fork-packager
11765 ◯ : gftools packager "Solitreo" fonts -p                                                                                                 [~]
Traceback (most recent call last):
  File "/Users/eli/Py/venvs/python3-venv-google-fonts/bin/gftools-packager.py", line 9, in <module>
    from gftools import packager
  File "/Users/eli/Py/venvs/python3-venv-google-fonts/lib/python3.9/site-packages/gftools/packager.py", line 24, in <module>
    import pygit2 # type: ignore
  File "/Users/eli/Py/venvs/python3-venv-google-fonts/lib/python3.9/site-packages/pygit2/__init__.py", line 30, in <module>
    from ._pygit2 import *
ImportError: dlopen(/Users/eli/Py/venvs/python3-venv-google-fonts/lib/python3.9/site-packages/pygit2/_pygit2.cpython-39-darwin.so, 0x0002): Library not loaded: '/opt/homebrew/opt/libgit2/lib/libgit2.1.1.dylib'
  Referenced from: '/Users/eli/Py/venvs/python3-venv-google-fonts/lib/python3.9/site-packages/pygit2/_pygit2.cpython-39-darwin.so'
  Reason: tried: '/opt/homebrew/opt/libgit2/lib/libgit2.1.1.dylib' (no such file), '/usr/local/lib/libgit2.1.1.dylib' (no such file), '/usr/lib/libgit2.1.1.dylib' (no such file), '/opt/homebrew/Cellar/libgit2/1.4.4/lib/libgit2.1.1.dylib' (no such file), '/usr/local/lib/libgit2.1.1.dylib' (no such file), '/usr/lib/libgit2.1.1.dylib' (no such file)
```

Expected behavior: pygit2 and other dependencies should be covered in the documentation.

This issue more generally is here to indicate I am working on improving the packager documentation.

**Comment by eliheuer** [comment]
I'm working on a big update to the packager documentation this week.

This covers more than just the issue above and aims to make the packager as user friendly and well documented as possible.

**Comment by RosaWagner** [comment]
If you have an issue with the packager, better to raise it in gftools repo. All dependencies should be installed with installing gftools, or following this chapter: googlefonts.github.io/gf-guide/tools.html.

**Comment by RosaWagner** [comment]
If it is not clear in the documentation then it needs to be clarified: packager creates branch directly in google/fonts repo and only people with contribution permission can do. So packager is useless to users without permission. This is not against users in general, this is the only protection that was found from people trying to break the CI (it happen several times last year).

They can do manual PRs but we don't have many ways to make sure they used the add-font script, and so better to re-do it ourself to ensure the metadata consistency.

**Comment by eliheuer** [comment]
But if you redo the PR yourself the user does not get credit for the PR in google/fonts. The PRs are what is visible to Google and GitHub as work. I know this is a fight I'm not going to win, the point of this issue is that the packager documentation needs improvement.

**Comment by eliheuer** [comment]
There is a book about this problem. In a large repo like google/fonts, you need to do work in a way where it will be seen up the chain of command, or it won't get noticed and appreciated.

![seeing-like-a-state](https://user-images.githubusercontent.com/5162664/191766255-c1c56d7e-f186-4b01-9737-300fb0e3dfea.jpeg)
