### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by appsforartists** [googlefonts/googlefonts.github.io#6]
https://googlefonts.github.io/fluid doesn't work anymore, presumably because this site is conflicting with its namespace.

Can we set it up so the index page exists without breaking links to old projects (and/or make updates so both can coexist)?

**Comment by rsheeter** [comment]
Forgive my density but where was that supposed to take you?

**Comment by vv-monsalve** [comment]
> https://googlefonts.github.io/fluid doesn't work anymore

@appsforartists, the page seems to be working now. I'm closing this issue here. Feel free to reopen it if you need to discuss something else.
