### ISSUE TITLE
Expand "GF" acronym to read "Google Fonts" for clarity

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/googlefonts.github.io#93]
The acronym "GF" is used frequently in the guide to refer to "Google Fonts".

In the interest of making the guide clear and understandable for first time readers and avoiding insider jargon I suggest expanding "GF" to read "Google Fonts".

**Comment by eliheuer** [comment]
If you read the GitHub Docs for example, they use the full name GitHub regularly instead of saying GH, but I'm almost certain GH is used in internal conversations. 

https://docs.github.com/en

**Comment by eliheuer** [comment]
Looking at the Google Maps documentation I don't think they ever call it GM: https://developers.google.com/maps/documentation

**Comment by RosaWagner** [comment]
Feel free to make a PR

**Comment by vv-monsalve** [comment]
The use of acronyms on many occasions, but especially in documentation, is precisely to simplify the reading process without cluttering it with many words that may sound redundant at one point. Here (in the Guide), it was used more as practicality for users than as an "insider jargon".

However, If you find this crucial, as Rosa said, please feel free to make a PR with a revision for the Guide.
