### ISSUE TITLE
New page: Promotion

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlefonts.github.io#96]
I expect upstreams to provide social media promotion imagery. I believe onboarding folks have been requesting these from upstreams, but I don't see any info in the guide currently on that part of the onboarding process. Let's confirm the various processes used to date in different projects, and add a new page about the final stage of onboarding: post-push promotion :)

**Comment by RosaWagner** [comment]
then it's this page to update: https://googlefonts.github.io/gf-guide/marketing.html

**Comment by vv-monsalve** [comment]
The before "marketing" section has been updated and renamed to [Promote your font](https://googlefonts.github.io/gf-guide/promotion.html) :)
